account/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import *


urlpatterns = [
    path('login/',account_login,name='login'),
    path('register/',account_register,name='register'),
    path('logout/',account_logout,name='logout'),
    
    path('members/',members_management,name='members'),
    path('members/add/',member_add,name='members_add'),
    path('members/curd/<int:record_id>/',member_curd,name='members_curd'),

    path('users/',users_index,name='users'),
    path('users/add/',users_add,name='users_add'),
    path('users/curd/<int:record_id>/',users_curd,name='users_curd'),
]

activity/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('details/<int:pk>/', activity_details, name='activitiy_details'),
    path('sendcomment/<int:pk>/', activity_sendcomment, name='activity_sendcomment'),
    path('index/', activity_index, name='activities'),
    path('create/', activity_create, name='activityCreate'),
    path('edit/<int:pk>/', activity_edit, name='activity_edit'),
    path('delete/<int:pk>/', activity_delete, name='activity_delete'),
    path('register/', activity_register, name='activity_register'),
    path('demo/', activity_demo),
    path('calendar/', activity_calendar, name='activity_calendar'),
    path('application/', activity_application, name='activity_application'),
    path('application/check/', activity_check, name='activity_check'),
    path('application/self/', activity_self, name='activity_self'),
]

admsApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
                  path('', include("dashboard.urls")),
                  path('admin/', admin.site.urls),
                  path('activity/', include("activity.urls")),
                  path('account/', include("account.urls")),
                  path('dashboard/', include("dashboard.urls")),
                  url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT})
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

activity/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone
from account.models import Accounts, Department
import datetime


# Create your models here.
class Activity(models.Model):
    title = models.CharField(max_length=200)
    # name = models.CharField(max_length=30)
    name = models.ForeignKey(Accounts, related_name="uname", on_delete=models.CASCADE, blank=False)
    # department = models.CharField(max_length=30, default='None')
    department = models.ForeignKey(Department, on_delete=models.SET_DEFAULT, default=1)
    short_descipt = models.CharField(max_length=200)
    expected_number = models.IntegerField(default=5)
    registered_members = models.ManyToManyField(Accounts)
    # content = RichTextField()
    post = models.TextField(default=None)
    # content_html = models.TextField(blank=True, editable=False)
    hold_time = models.DateField(default=datetime.date.today)
    publish_time = models.DateTimeField(auto_now_add=True)
    last_edit_time = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(default=timezone.now)
    passed = models.BooleanField(default=False)
    comment = models.CharField(max_length=200, default=None, blank=True, null=True)
    # comment_user = models.CharField(max_length=30, default=None, blank=True, null=True)
    comment_user = models.ForeignKey(Accounts, related_name="comment_user", on_delete=models.CASCADE, blank=True)
    pic = models.ImageField(height_field=None, width_field=None, max_length=None, blank=True, null=True,
                            default='/media/smile.png')

    def __str__(self):
        return self.title


class Comments(models.Model):
    account = models.ForeignKey(Accounts, on_delete=models.CASCADE, blank=False)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE, blank=False)
    commentstr = models.CharField(max_length=200, blank=False, null=False)
    deadline = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.commentstr

activity/forms.py
from django.forms import ModelForm, Textarea, CharField, TextInput, DateInput, EmailInput, Select, PasswordInput, \
    SelectMultiple

from account.models import Accounts, Department
from .models import Activity

# department_choices = (
#     ('publicity', 'Publicity'), ('security', 'Security'), ('entertainment', 'Entertainment'),
#     ('secretary', 'Secretary'),
#     ('volunteer', 'Volunteer'), ('journalist', 'Journalist'))
department_choices = []
try:
    for item in Department.objects.all():
        department_choices.append((item.name, item.name))
except:
    pass

AccountsTemple = []
try:
    for item in Accounts.objects.all():
        AccountsTemple.append(item.name)
except:
    pass


class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = ['title', 'department', 'short_descipt', 'expected_number', 'hold_time', 'post', 'deadline',
                  'registered_members', 'pic']
        labels = {
            'short_descipt': 'Short description',
            'post': 'Content',
            'pic': 'Picture',
            'expected_number': 'Expected number of staff',
            'hold_time': 'Holding time',
            'registered_members': 'Participants'
        }
        widgets = {
            'department': Select(choices=department_choices, attrs={'class': 'form-control'}),
            'registered_members': SelectMultiple(choices=AccountsTemple, attrs={'class': 'form-control'}),
        }
        help_texts = {
            'registered_members': 'Press command key to multiselect',
        }

    def __init__(self, *args, **kwargs):
        super(ActivityForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if not field_name == 'registered_members':
                self.fields[field_name].widget.attrs['class'] = 'form-control'

# class ActivityEditForm():
#     class Meta:
#         model = Activity
#         fields = ['title','department', 'short_descipt','expected_number','hold_time','post','deadline','pic']
#         labels ={
#             'short_descipt': 'Short description',
#             'post': 'Content',
#             'pic':'Picture',
#             'expected_number':'Expected number of staff',
#             'hold_time':'Holding time'
#         }
#         widgets = {


#             'department':Select(choices=department_choices,attrs={'class':'form-control','placeholder':'department'}),


#         }

activity/views.py
from django.shortcuts import render, redirect
from .models import Activity, Comments
from .forms import ActivityForm
from .table import activityTable, applicationTable, selfApplicationTable
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from account.models import Accounts
from django.db.models import Q


# Create your views here.
def activity_index(request):
    content = request.GET.get('content', '')
    queryset = Activity.objects.filter(passed=True).order_by('-hold_time')
    if content:
        queryset = queryset.filter(
            Q(title__icontains=content) | Q(department__icontains=content) | Q(name__icontains=content) | Q(
                short_descipt__icontains=content))

    table = activityTable(queryset)

    return render(request, 'activity/index.html', {'table': table, 'content': content})


# activity create
@login_required
def activity_create(request):
    form = ActivityForm()
    if not request.META['REQUEST_METHOD'] == 'POST':
        return render(request, 'activity/create.html', {'form': form})

    try:
        actform = ActivityForm(request.POST)
        print("actform.errors：", actform.errors)
        if actform.is_valid():
            activity = actform.save(commit=False)
            # activity.department = actform.cleaned_data.get('department')
            # activity.short_descipt = actform.cleaned_date.get('short_descipt')
            # activity.expected_number = actform.cleaned_date.get('expected_number')
            # activity.hold_time = actform.cleaned_date.get('hold_time')
            # activity.post = actform.cleaned_date.get('post')
            # activity.deadline = actform.cleaned_date.get('deadline')

            registered_members_ids = request.POST.get("choose_userid").split(',')

            activity.name = Accounts.objects.filter(name=request.user.username).first()
            activity.registered_number = 0
            pic = request.FILES.get('pic', None)
            if pic:
                print('addpic')
                fSystem = FileSystemStorage()
                newPic = fSystem.save(pic.name, pic)
                newPic_url = fSystem.url(newPic)
                activity.pic = newPic_url
            if request.user.is_superuser:
                activity.passed = True
                activity.comment = "Agree"
                activity.comment_user = Accounts.objects.filter(name=request.user.username).first()
            activity.save()
            for id in registered_members_ids:
                activity.registered_members.add(int(id))
            activity.save()
            print('save successfully')
            return redirect('activitiy_details', pk=activity.pk)
        else:
            print('form is not valid')
        return redirect('activities')
    except Exception as e:
        print(e)
        return render(request, 'activity/create.html', {'form': form, 'ErrorMsg': "System Error"})


# activity index
def activity_details(request, pk):
    activity = Activity.objects.get(id=pk)
    comments = Comments.objects.filter(activity=activity).order_by('-deadline')
    return render(request, 'activity/details.html', {'activity': activity, 'comments': comments})


def activity_sendcomment(request, pk):
    activity = Activity.objects.get(id=pk)
    if not request.META['REQUEST_METHOD'] == 'POST':
        return redirect('/activity/index/')
    else:
        account = Accounts.objects.get(name=request.user.username)
        commentstr = request.POST.get('commentstr', '')
        if commentstr:
            Comments.objects.create(
                account=account,
                activity=activity,
                commentstr=commentstr
            ).save()
        return redirect('/activity/details/%s/' % pk)


# activity edit
def activity_edit(request, pk):
    activity = Activity.objects.get(id=pk)
    if not request.META['REQUEST_METHOD'] == 'POST':

        form = ActivityForm(instance=activity)
        return render(request, 'activity/create.html', {'activity': activity, 'form': form, 'edit': True})
    else:
        pic = request.FILES.get('pic', None)
        if pic:
            fSystem = FileSystemStorage()
            newPic = fSystem.save(pic.name, pic)
            newPic_url = fSystem.url(newPic)
            activity.pic = newPic_url
        actform = ActivityForm(request.POST, instance=activity)
        activity = actform.save(commit=False)
        activity.save()
        print('save successfully')
        return redirect('activitiy_details', pk=activity.pk)


# activity delete
def activity_delete(request, pk):
    activity = Activity.objects.get(pk=pk)
    activity.delete()
    print('delete successfully')
    return redirect('activities')


def activity_register(request):
    if not request.META['REQUEST_METHOD'] == 'POST':
        return redirect('activities')
    pk = request.POST.get('pk', None)
    if pk:
        try:
            activity = Activity.objects.get(pk=pk)
            # print(activity.registered_members.count())
            account = Accounts.objects.get(name=request.user.username)
            activity.registered_members.add(account)
            activity.save()

            print('register successfully')
            return redirect('activitiy_details', pk=activity.pk)
        except Exception as e:
            print(e)
    else:
        print("pk error")
    return redirect('activities')


def activity_calendar(request):
    all_activites = Activity.objects.filter(passed=True)

    return render(request, 'activity/calendar.html', {'activities': all_activites})


def activity_application(request):
    content = request.GET.get('content', '')
    queryset = Activity.objects.filter(passed=False).order_by('-hold_time')
    if content:
        queryset = queryset.filter(
            Q(title__icontains=content) | Q(department__icontains=content) | Q(name__icontains=content) | Q(
                short_descipt__icontains=content))

    table = applicationTable(queryset)

    return render(request, 'activity/applications.html', {'table': table, 'content': content})


def activity_check(request):
    if not request.META['REQUEST_METHOD'] == 'POST':
        return redirect('activities')
    pk = request.POST.get('pk', None).replace('/', '')
    comment = request.POST.get('comment', None)
    if pk:
        passed = request.POST.get('passed')
        try:
            activity = Activity.objects.get(pk=pk)
            if passed == 'on':
                activity.passed = True
            else:
                activity.passed = False
            activity.comment = comment
            activity.comment_user = Accounts.objects.filter(name=request.user.username).first()
            activity.save()
            return redirect('activitiy_details', pk=activity.pk)

        except Exception as e:
            print(e)
            return redirect('activities')


def activity_self(request):
    content = request.GET.get('content', '')
    queryset = Activity.objects.filter(registered_members__name__in=[request.user.username]).order_by('-hold_time')
    print(queryset)
    print(request.user.username)
    if content:
        queryset = queryset.filter(
            Q(title__icontains=content) | Q(department__icontains=content) | Q(name__icontains=content) | Q(
                short_descipt__icontains=content))
    table = selfApplicationTable(queryset)

    return render(request, 'activity/applications.html', {'table': table, 'content': content})


def activity_demo(request):
    return render(request, 'activity/demo.html')

templates/activity/applications.html
{% extends '../base/index.html'%}
{% load django_tables2 %}

{% block content_header %}
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Activities</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Activity</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block main_content %}  
  <div class="content">
      <div class="container-fluid">
        <div class="card">
    
    
    <div class="card-body">
    <div class="row">
        <div class="col-sm-12 col-sm-12 offset-md-9 col-md-3 mb-3 ">
            
           <form class="form-inline ml-3" method='GET' action='{% url "activities" %}'>
              <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" name ='content' type="search" placeholder="search" aria-label="Search" value='{{content}}'>
                <div class="input-group-append">
                 <button class="btn btn-navbar" type="submit">
                 <i class="fas fa-search"></i>
                 </button>
                </div>
             </div>
           </form> 

        </div>
    </div>
      
    {% render_table table %}
    
    </div>
        
</div>
      </div>
</div>

{% endblock %}

templates/activity/calendar.html
{% extends '../base/index.html'%}
{% load static %}
{% load django_tables2 %}
{% block external_style %}
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar/main.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar/main.css' %}">

  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
{% endblock %}

{% block content_header %}
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Calendar</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Activity</li>
              <li class="breadcrumb-item active">Calendar</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
{% endblock %}



{% block main_content %}

<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-2">
            <div class="sticky-top mb-3">
              <div class="card">
                <div class="card-header">
                  <h4 class="card-title">Information</h4>
                </div>
                <div class="card-body">
                {% for i in events %}
                {{i.expected_number}}
                {% endfor %}
                        <a class="text-danger" ><i class="fas fa-square"></i></a> :Full <br>
                        <a class="text-success" ><i class="fas fa-square"></i></a> :Avaiable <br>
                        <a class="text-grey" ><i class="fas fa-square"></i></a> :Invalid <br>
                    

                  <!-- the events -->
                  {% comment %} <div id="external-events">
                    <div class="external-event bg-success ui-draggable ui-draggable-handle" style="position: relative; z-index: auto; left: 0px; top: 0px;">Lunch</div>
                    <div class="external-event bg-warning ui-draggable ui-draggable-handle" style="position: relative; z-index: auto; left: 0px; top: 0px;">Go home</div>
                    <div class="external-event bg-info ui-draggable ui-draggable-handle" style="position: relative;">Do homework</div>
                    <div class="external-event bg-primary ui-draggable ui-draggable-handle" style="position: relative; z-index: auto; left: 0px; top: 0px;">Work on UI design</div>
                    <div class="external-event bg-danger ui-draggable ui-draggable-handle" style="position: relative; z-index: auto; left: 0px; top: 0px;">Sleep tight</div>
                    <div class="checkbox">
                      <label for="drop-remove">
                        <input type="checkbox" id="drop-remove">
                        remove after drop
                      </label>
                    </div>
                  </div> {% endcomment %}
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title"> Management</h3>
                </div>
                <div class="card-body">
                  <a class='btn btn-primary' style="width: 100%; margin-bottom: 10px;" href='{% url 'activityCreate' %}'>Create </a>
                 <a class='btn btn-success' style="width: 100%; margin-bottom: 10px;" href='{% url 'activities' %}'>Detail </a>
                
                  
                </div>
              </div>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-md-10">
            <div class="card card-primary">
              <div class="card-body p-0">
                <!-- THE CALENDAR -->
                <div id="calendar"></div>
                
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!--list calendar-->
            <div class='card card-primary'>
                <div class="card-body p-0">
                    <div id='listCalendar'>
                    </div>
                </div>
            </div>
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
{% endblock %}



{% block externalScript %}

<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/fullcalendar/main.min.js' %} "></script>
<script src="{% static 'plugins/fullcalendar/main.js' %} "></script>

<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>

{% endblock %}

{% block staticfile_script %}

document.addEventListener('DOMContentLoaded', function() {
        var calendarEI = document.getElementById('calendar');
        var listCalendarEI = document.getElementById('listCalendar');
        var calendar = new FullCalendar.Calendar(calendarEI, {
          initialView: 'dayGridMonth',
          editable: true,
          eventLimit: true,
          
          events: [
                {% for i in activities %}
                   {
                    title: '{{i.title}}',
                    start: ' {{ i.hold_time|date:"Y-m-d" }}',
                    id:{{i.pk}},
                    expected: {{i.expected_number}},
                    registered: {{i.registered_members.count}},
                    
                
                }, 
               
                {% endfor %}
               
                ],
          eventClick: function(info) 
           {
              window.open("/activity/details/"+info.event.id);
             {% comment %} window.location.href = "/activity/details/"+info.event.id; {% endcomment %}
            }, 
          eventDidMount: function(info) 
           {
              var todayDate = new Date();
              if(info.event.start < todayDate)
              {
                // Change background color of row
                info.el.style.backgroundColor = 'grey';
                
              }

                else{
                    info.el.style.backgroundColor = 'green';
                    console.log(info.event.expected_number );
                    console.log(info.event.id );
                }
    if(info.event._def.extendedProps.registered >= info.event._def.extendedProps.expected)
                {
                    info.el.style.backgroundColor = 'red';
                }
            }
  
        });

        


        var listCalendar = new FullCalendar.Calendar(listCalendarEI, {
          initialView: 'listWeek',
          
          events: [
                {% for i in activities %}
                   {
                    title: '{{i.title}}',
                    start: ' {{ i.hold_time|date:"Y-m-d" }}',
                    
                }, 
               
                {% endfor %}
               
                ],
        
        });
        calendar.render();
        listCalendar.render();
});


  
{% endblock %}

templates/activity/create.html
{% extends '../base/index.html' %}
{% load django_tables2 %}

{% block content_header %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Activities</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">Activity</li>
                        <li class="breadcrumb-item active">{{ activity.title }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block main_content %}
    <div class="content">
        <div class="container-fluid">
            <div class="row d-flex justify-content-center ">
                <div class="card col-11">
                    <div class="card-header">

                        {% if edit %}
                            <h3 class="card-title "> Edit activity</h3>
                        {% else %}
                            <h3 class="card-title "> Create activity</h3>
                        {% endif %}
                        <div class="card-tools">


                        </div>
                    </div>
                    {% if edit %}
                        <form action={% url "activity_edit" pk=activity.pk %} method='post'
                              enctype="multipart/form-data">
                    {% else %}
                        <form action='{% url "activityCreate" %}' method='post' enctype="multipart/form-data">
                    {% endif %}
                    {% csrf_token %}
                    <div class="card-body">
                        <div class='row d-flex justify-content-center'>
                            <div class='col-8 m-1'>
                                <input value="" id="choose_userid" name="choose_userid" style="display: none;"/>
                                {% for field in form %}
                                    <div class="form-group row">
                                        <label for="{{ field.id_for_label }}"
                                               class="col-4 col-form-label">{{ field.label }}:</label>
                                        <div class="col-8">
                                            {{ field }}
                                            {{ field.help_text }}
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <span style="color: red;">{{ ErrorMsg }}</span>
                        <input type="submit" class="btn btn-primary float-right editor-style" id="createBtn"
                               value="Save"/>
                    </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

{% endblock %}
{% block external_style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
{% endblock %}
{% block externalScript %}
    {% load static %}

    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>

    <script src="{% static 'plugins/bootstrap-select/js/bootstrap-select.js' %}"></script>
    <script>
        //用于判断选择哪些用户
        $("#id_registered_members").change(function () {
            o = document.getElementById("id_registered_members");
            var intvalue = "";
            for (i = 0; i < o.length; i++) {
                if (o.options[i].selected) {
                    intvalue += o.options[i].value + ",";
                }
            }
            $("#choose_userid").val(intvalue.substr(0, intvalue.length - 1))
        })
    </script>

{% endblock %}

{% block staticfile_script %}

    $(function() {
    $('input[name="hold_time"]').daterangepicker({
    singleDatePicker: true,
    showDropdowns: true,
    minYear: 2021,
    maxYear: parseInt(moment().format('YYYY'),10),
    locale: {
    format: 'YYYY-MM-DD'

    }
    }, function(start, end, label) {
    {% comment %} can do something  {% endcomment %}
    });
    $('input[name="deadline"]').daterangepicker({
    singleDatePicker: true,
    showDropdowns: true,
    timePicker:true,
    minYear: 2021,
    maxYear: parseInt(moment().format('YYYY'),10),
    locale: {
    format: 'YYYY-MM-DD hh:mm:ss'

    }
    }, function(start, end, label) {

    {% comment %} can do something  {% endcomment %}
    });


    });

{% endblock %}

templates/activity/demo.html
{% extends '../base/index.html'%}

templates/activity/index.html
{% extends '../base/index.html'%}
{% load django_tables2 %}

{% block content_header %}
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Activities</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Activity</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block main_content %}  
  <div class="content">
      <div class="container-fluid">
        <div class="card">
    
    
    <div class="card-body">
    <div class="row">
        <div class="col-sm-12 col-sm-12 col-md-3 mb-3 ">    
            
            <a class='btn btn-primary' href='{% url 'activityCreate' %}'>Create an activity</a>
            
        </div>
        <div class="col-sm-12 col-sm-12 offset-md-6 col-md-3 mb-3 ">
            
           <form class="form-inline ml-3" method='GET' action='{% url "activities" %}'>
              <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" name ='content' type="search" placeholder="search" aria-label="Search" value='{{content}}'>
                <div class="input-group-append">
                 <button class="btn btn-navbar" type="submit">
                 <i class="fas fa-search"></i>
                 </button>
                </div>
             </div>
           </form> 

        </div>
    </div>
      
    {% render_table table %}
    
    </div>
        
</div>
      </div>
</div>

{% endblock %}